setwd("C:/github/jfsp/www")
library(Cairo)
library(showtext)
font.add("cam", "cambriaz.TTF")
showtext.auto()

set.seed(1)
xlm <- c(-4.5, 4.5)
x <- seq(xlm[1], xlm[2], length=1000)
y <- dnorm(x)
x2 <- rnorm(500000)
x2 <- x2[x2 > xlm[1] & x2 < xlm[2]]
mar <- c(0.1, 0.1, 0.1 ,0.1)

# Code is repetetive and includes hardcoded values because each icon is uniquely tailored,
# for example, for proper text placement.
makeIcons <- function(primary_color="#FFFFFF", secondary_color="#FFFFFF75", color_theme="white"){
  CairoPNG(paste0("stat_icon_normal_dist_", color_theme, ".png"), width=96, height=96, bg="transparent")
  par(lwd=2, mar=mar, family="cam")
  plot(x, y, type="n", axes=FALSE, xlab="", ylab="", xlim=xlm)
  hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=primary_color)
  lines(x, y, col=primary_color)
  dev.off()
  
  CairoPNG(paste0("stat_icon_normal_mean_", color_theme, ".png"), width=96, height=96, bg="transparent")
  par(lwd=2, mar=mar, family="cam")
  plot(x, y, type="n", axes=FALSE, xlab="", ylab="", xlim=xlm)
  hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=secondary_color)
  lines(x, y, col=secondary_color)
  abline(v=0, lwd=3, lty=2, col=primary_color)
  legend("topright", legend=expression(bolditalic(bar(x))), bty ="n", pch=NA, cex=3,  yjust=1, adj=c(-0.5, 0), text.col=primary_color)
  dev.off()
  
  CairoPNG(paste0("stat_icon_normal_min_", color_theme, ".png"), width=96, height=96, bg="transparent")
  par(lwd=2, mar=mar, family="cam")
  plot(x, y, type="n", axes=FALSE, xlab="", ylab="", xlim=xlm)
  hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=secondary_color)
  lines(x, y, col=secondary_color)
  abline(v=xlm[1], lwd=3, lty=2, col=primary_color)
  legend("topright", legend=expression(bolditalic(x[(1)])), bty ="n", pch=NA, cex=1.8, adj=c(-0.275, 0), text.col=primary_color)
  dev.off()
  
  CairoPNG(paste0("stat_icon_normal_max_", color_theme, ".png"), width=96, height=96, bg="transparent")
  par(lwd=2, mar=mar, family="cam")
  plot(x, y, type="n", axes=FALSE, xlab="", ylab="", xlim=xlm)
  hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=secondary_color)
  lines(x, y, col=secondary_color)
  abline(v=xlm[2], lwd=3, lty=2, col=primary_color)
  legend("topleft", legend=expression(bolditalic(x[(n)])), bty ="n", pch=NA, cex=1.8,  adj=c(1, 0), text.col=primary_color)
  dev.off()
  
  CairoPNG(paste0("stat_icon_normal_median_", color_theme, ".png"), width=96, height=96, bg="transparent")
  par(lwd=2, mar=mar, family="cam")
  plot(x, y, type="n", axes=FALSE, xlab="", ylab="", xlim=xlm)
  hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=secondary_color)
  lines(x, y, col=secondary_color)
  abline(v=0, lwd=3, lty=2, col=primary_color)
  legend("topright", legend=expression(bolditalic(tilde(x))), bty ="n", pch=NA, cex=3,  adj=c(-0.5, 0), text.col=primary_color)
  dev.off()
  
  CairoPNG(paste0("stat_icon_normal_sd_", color_theme, ".png"), width=96, height=96, bg="transparent")
  par(lwd=2, mar=mar, family="cam")
  plot(x, y, type="n", axes=FALSE, xlab="", ylab="", xlim=xlm)
  hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=secondary_color)
  lines(x, y, col=secondary_color)
  abline(v=c(-1,1), lwd=3, lty=2, col=primary_color)
  legend("topright", legend=expression(bolditalic(hat(s))), bty="n", pch=NA, cex=3, adj=c(-0.5, 0), text.col=primary_color)
  dev.off()
  
  showtext.auto(enable=FALSE)
  
  CairoPNG(paste0("stat_icon_boxplot_iqr_", color_theme, ".png"), width=96, height=96, bg="transparent")
  par(lwd=2, mar=mar, family="cam")
  boxplot(x2, outline=FALSE, axes=FALSE, frame=FALSE,  lty=1, border=secondary_color, boxcol=primary_color)
  text(1.35, -0.05, expression("}"), cex=2, col=primary_color)
  showtext.begin()
  text(1.35, 1.5, expression("IQR"), cex=1.5, col=primary_color)
  showtext.end()
  dev.off()
  
  showtext.auto()
}

makeIcons()
makeIcons("black", "gray30", "black")
