setwd("C:/github/jfsp/www")
library(Cairo)
library(showtext)
font.add("cam", "cambriaz.TTF")
showtext.auto()

set.seed(1)
xlm <- c(-4.5, 4.5)
x <- seq(xlm[1], xlm[2], length=1000)
y <- dnorm(x)
x2 <- rnorm(500000)
x2 <- x2[x2 > xlm[1] & x2 < xlm[2]]
clr1 <- "#FFFFFF"
clr2 <- "#FFFFFF75"
mar <- c(0.1, 0.1, 0.1 ,0.1)

CairoPNG("stat_icon_normal_dist.png", width=96, height=96, bg="transparent")
par(lwd=2, mar=mar, family="cam")
plot(x, y, type="n", axes=F, xlab="", ylab="", xlim=xlm)
hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=clr1)
lines(x, y, col=clr1)
dev.off()

CairoPNG("stat_icon_normal_mean.png", width=96, height=96, bg="transparent")
par(lwd=2, mar=mar, family="cam")
plot(x, y, type="n", axes=F, xlab="", ylab="", xlim=xlm)
hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=clr2)
lines(x, y, col=clr2)
abline(v=0, lwd=3, col=clr1)
legend("topright", legend=expression(bolditalic(bar(x))), bty ="n", pch=NA, pt.cex=0.5, cex=3,  yjust=1, adj=c(-0.5, 0), text.col=clr1)
dev.off()

CairoPNG("stat_icon_normal_min.png", width=96, height=96, bg="transparent")
par(lwd=2, mar=mar, family="cam")
plot(x, y, type="n", axes=F, xlab="", ylab="", xlim=xlm)
hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=clr2)
lines(x, y, col=clr2)
abline(v=xlm[1], lwd=3, lty=2, col=clr1)
legend("topright", legend=expression(bolditalic(x[(1)])), bty ="n", pch=NA, pt.cex=0.5, cex=1.8, adj=c(-0.275, 0), text.col=clr1)
dev.off()

CairoPNG("stat_icon_normal_max.png", width=96, height=96, bg="transparent")
par(lwd=2, mar=mar, family="cam")
plot(x, y, type="n", axes=F, xlab="", ylab="", xlim=xlm)
hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=clr2)
lines(x, y, col=clr2)
abline(v=xlm[2], lwd=3, lty=2, col=clr1)
legend("topleft", legend=expression(bolditalic(x[(n)])), bty ="n", pch=NA, pt.cex=0, cex=1.8,  adj=c(1, 0), text.col=clr1)
dev.off()

CairoPNG("stat_icon_normal_median.png", width=96, height=96, bg="transparent")
par(lwd=2, mar=mar, family="cam")
plot(x, y, type="n", axes=F, xlab="", ylab="", xlim=xlm)
hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=clr2)
lines(x, y, col=clr2)
abline(v=0, lwd=3, col=clr1)
legend("topright", legend=expression(bolditalic(tilde(x))), bty ="n", pch=NA, pt.cex=0.5, cex=3,  adj=c(-0.5, 0), text.col=clr1)
dev.off()

CairoPNG("stat_icon_normal_sd.png", width=96, height=96, bg="transparent")
par(lwd=2, mar=mar, family="cam")
plot(x, y, type="n", axes=F, xlab="", ylab="", xlim=xlm)
hist(x2, breaks=seq(xlm[1], xlm[2], by=1), freq=FALSE, add=TRUE, border=clr2)
lines(x, y, col=clr2)
abline(v=c(-1,1), lwd=3, col=clr1)
legend("topright", legend=expression(bolditalic(hat(s))), bty="n", pch=NA, pt.cex=0, cex=3, adj=c(-0.5, 0), text.col=clr1)
dev.off()

showtext.auto(enable=FALSE)

CairoPNG("stat_icon_boxplot_iqr.png", width=96, height=96, bg="transparent")
par(lwd=2, mar=mar, family="cam")
boxplot(x2, outline=FALSE, axes=FALSE, frame=FALSE,  lty=1, border=clr2, boxcol=clr1)
text(1.35, -0.05, expression("}"), cex=2, col=clr1)
showtext.begin()
text(1.35, 1.5, expression("IQR"), cex=1.5, col=clr1)
showtext.end()
dev.off()
